### ISSUE TITLE
API container stuck restarting

### ISSUE THREAD

**Issue by graham-walker** [getumbrel/llama-gpt#10]
OS: Windows 10 22H2
CPU: 9900K
RAM: 32 GB

Attempted the install from commit [c9cfd24](https://github.com/getumbrel/llama-gpt/commit/c9cfd24234a0ecd058dfc3cee0ff4f39ad192030)
```
git clone https://github.com/getumbrel/llama-gpt.git
cd llama-gpt
docker compose -f docker-compose-13b.yml up -d
```

The container llama-gpt-llama-gpt-api-1 does not start, and is stuck in a restart loop repeating:
```
: not found19:41:13 /app/run.sh: 2: 
'.  Stop.6 19:41:13 make: *** No rule to make target 'build
: not found19:41:13 /app/run.sh: 4: 
: not found19:41:13 /app/run.sh: 7: 
: not found19:41:13 /app/run.sh: 10: 
: not found19:41:13 /app/run.sh: 13: 
2023-08-16 19:41:13 /app/run.sh: 29: Syntax error: end of file unexpected (expecting "then")
```

**Comment by m4thfr34k** [comment]
Same result

OS: Windows 11 Pro
CPU: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz   3.40 GHz
RAM: 128 GB

**Comment by wscottcarl** [comment]
I'm getting the same restart loop in the API.

OS: Windows 10 22H2
CPU: AMD Ryzen 5 2600
RAM: 16 GB

**Comment by JustinTisdale** [comment]
Same issue here with both the 7b and 13b docker-compose files.

OS: Windows 10 22H2
CPU: AMD Ryzen 9 5900X
RAM: 32 GB

**Comment by mghazalyh** [comment]
OS: Windows 10 22H2
CPU: AMD Ryzen 9 5900X
RAM: 32 GB

![image](https://github.com/getumbrel/llama-gpt/assets/102565216/b2843087-2761-4656-8111-0178785b2a0a)

![image](https://github.com/getumbrel/llama-gpt/assets/102565216/d113bfac-8165-4921-ba01-b66ec59cfe82)

**Comment by wscottcarl** [comment]
The tab on run.sh's line 19 is being converted to spaces in the image itself. When I manually changed the file in an Exited container and restarted it, I ran into a new error message.

**Comment by Vitazema** [comment]
fix for windows users:
1) Git bash into /api/ folder
2) run dos2unix /run.sh
3) docker compose up -d --build

**Comment by mghazalyh** [comment]
> fix for windows users:
> 
> 1. Git bash into /api/ folder
> 2. run dos2unix /run.sh
> 3. docker compose up -d --build

thank you for the assist, it works now.

**Comment by mayankchhabra** [comment]
Thanks everyone for reporting the issue, and thanks for suggesting the fix @Vitazema! We've fixed this by adding a `.gitattributes` file (339cf66be6264b5bbfdd846a48dca82ca901f9c7) that enforces consistent line endings across files between Unix and Windows.

**Comment by jodiecunningham** [comment]
Thanks for the update!  

Windows users:   Even if you've done a git pull for the latest version, you should run the previous step 3:    `docker compose up -d --build`
