### ISSUE TITLE
Question: Can Llama GPT (docker) use multiple GPUs?

### ISSUE THREAD

**Issue by stratus-ss** [getumbrel/llama-gpt#101]
As per the question above, I know basically nothing about how this stuff works. Is it even possible to use multiple GPUs in the cuda container to provide more performance?

Thanks!

**Comment by arch1v1st** [comment]
@stratus-ss - Personally, IDK, but I did just summarize some key settings I discovered here:

https://github.com/getumbrel/llama-gpt/issues/75
