### ISSUE TITLE
Unable to run code-34b 

### ISSUE THREAD

**Issue by coderj001** [getumbrel/llama-gpt#109]
I'm running it on GCP 32GB ram and 8 CPU. If any details reqired ping me.
![image](https://github.com/getumbrel/llama-gpt/assets/39460245/02dd8cf2-d76f-427d-a1e8-210c52408c55)
![image](https://github.com/getumbrel/llama-gpt/assets/39460245/0373ac39-2d0e-4b94-9229-4db2aca3fda7)
![image](https://github.com/getumbrel/llama-gpt/assets/39460245/cc940d2e-173a-456d-8e11-8ca46ced5215)

**Comment by eike-fokken** [comment]
Same for me.

**Comment by stratus-ss** [comment]
the speed it comes up depends on your internet connection. By default there is a timeout setting in the scripts that is something like 10,000 seconds. If your internet is slow you might need to pre-download the model into the models directory or find the settings inside the code that changes the timeout

**Comment by martijnED** [comment]
@stratus-ss thats not le issue, here is more of the error. Some protected namespace issue:

```
llama-gpt-llama-gpt-api-1  | /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_alias" has conflict with protected namespace "model_".
llama-gpt-llama-gpt-api-1  | 
llama-gpt-llama-gpt-api-1  | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
llama-gpt-llama-gpt-api-1  |   warnings.warn(
```

**Comment by martijnED** [comment]
solution: https://github.com/getumbrel/llama-gpt/issues/98#issuecomment-1715494487

**Comment by martijnED** [comment]
my advise close this issue
