### ISSUE TITLE
Memory usage low while machine has 64GB using 7B model

### ISSUE THREAD

**Issue by frasergr** [getumbrel/llama-gpt#16]
I noticed during generation that the RAM usage was only around 4.5GB. My machine has 64GB. Is there a way to allow for higher memory usage? Would this increase the tps at all?

**Comment by mayankchhabra** [comment]
The 7B model only needs about ~4.5GB. If you wanna try bigger models, you can try running the 13B and 70B variants which consume a lot higher memory as per the instructions here: https://github.com/getumbrel/llama-gpt#install-llamagpt-anywhere-else

**Comment by frasergr** [comment]
@mayankchhabra Thanks!
