### ISSUE TITLE
Wiki for examples for using api in python

### ISSUE THREAD

**Issue by bolavefasfas** [getumbrel/llama-gpt#21]
This repo is amazing no matter how many stars you give they are less
Even a single example is enough in this replu as well 

#feature request
Ability to select models from higgingface 
like wizard uncensored ggml 7b or 13 b 
one varible to setup in compose or web ui then we can chage models like oogaboga it will auto download and we can run it.

Thanks for this amazing project.

**Comment by bolshoytoster** [comment]
@bolavefasfas this project uses [llama-cpp-python](https://pypi.org/project/llama-cpp-python/) for the backend, you can see the documentation there.

**Comment by mayankchhabra** [comment]
Thanks @bolavefasfas. The API ports are now exposed (https://github.com/getumbrel/llama-gpt/commit/29199836c455d051a78a6fd574729f8631633ac4) at `http://localhost:3001`. You can open `http://localhost:3001/docs` to view the documentation.
