### ISSUE TITLE
is it possible that we can run this on colab and with gradio link 

### ISSUE THREAD

**Issue by Arifsha40** [getumbrel/llama-gpt#29]
is it possible that we can run this on colab and with gradio link 

can some one pls make it happen ?

**Comment by samuellukudu** [comment]
You may want to check this github repo, [text-generation-webui-colab](https://github.com/camenduru/text-generation-webui-colab) It has the colab and gradio UI for all the open source LLM models

**Comment by Arifsha40** [comment]
thank you ..
