### ISSUE TITLE
Run with models without censorship 

### ISSUE THREAD

**Issue by 21orangehat** [getumbrel/llama-gpt#32]
Hey guys,

Thank you for one more great app!

Is there a way to load and run models that are not following the OpenAI censorship mechanisms?

For example, the models that we have now are censored and would be nice if we could, easily, load
and use other models that will follow or not any censorship mechanism. 

This model https://huggingface.co/NousResearch/GPT4-x-Vicuna-13b-4bit, for instance, is not censored. But I didn't
find a way, yet, to load and use it.

[]'s

**Comment by bolshoytoster** [comment]
@21orangehat if you've downloaded the model you could try reading [my reply to a similar issue](https://github.com/getumbrel/llama-gpt/issues/35#issuecomment-1685122089) that may work.

**Comment by SyDant** [comment]
yup i want to run it without censorship
