### ISSUE TITLE
Assertion error in windows

### ISSUE THREAD

**Issue by Shahzaib-Hasaan** [getumbrel/llama-gpt#60]
llama-gpt-llama-gpt-api-7b-1  | Traceback (most recent call last):
llama-gpt-llama-gpt-api-7b-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
llama-gpt-llama-gpt-api-7b-1  |   File "<frozen runpy>", line 88, in _run_code
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/server/__main__.py", line 46, in <module>
llama-gpt-llama-gpt-api-7b-1  |     app = create_app(settings=settings)
llama-gpt-llama-gpt-api-7b-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/server/app.py", line 317, in create_app
llama-gpt-llama-gpt-api-7b-1  |     llama = llama_cpp.Llama(
llama-gpt-llama-gpt-api-7b-1  |             ^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  |   File "/app/llama_cpp/llama.py", line 328, in __init__
llama-gpt-llama-gpt-api-7b-1  |     assert self.model is not None
llama-gpt-llama-gpt-api-7b-1  |            ^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-7b-1  | AssertionError

**Comment by QuartzWarrior** [comment]
same error except on linux (Ubuntu 22.04.3 LTS aarch64)

**Comment by vanl0003** [comment]
Same here (in Windows).  Keeps looping between:

lllama-gpt-llama-gpt-ui-1       | [INFO  wait] Host [llama-gpt-api-13b:8000] not yet available...
llama-gpt-llama-gpt-ui-1       | [INFO  wait] Host [llama-gpt-api-13b:8000] not yet available...
llama-gpt-llama-gpt-ui-1       | [INFO  wait] Host [llama-gpt-api-13b:8000] not yet available...

and then the assertion error

llama-gpt-llama-gpt-api-13b-1  | /usr/local/lib/python3.11/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
llama-gpt-llama-gpt-api-13b-1  | !!
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-13b-1  |         Please avoid running ``setup.py`` and ``easy_install``.
llama-gpt-llama-gpt-api-13b-1  |         Instead, use pypa/build, pypa/installer or other
llama-gpt-llama-gpt-api-13b-1  |         standards-based tools.
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |         See https://github.com/pypa/setuptools/issues/917 for details.
llama-gpt-llama-gpt-api-13b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | !!
llama-gpt-llama-gpt-api-13b-1  |   easy_install.initialize_options(self)
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | [0/1] Install the project...
llama-gpt-llama-gpt-api-13b-1  | -- Install configuration: "Release"
llama-gpt-llama-gpt-api-13b-1  | -- Up-to-date: /app/_skbuild/linux-x86_64-3.11/cmake-install/llama_cpp/libllama.so
llama-gpt-llama-gpt-api-13b-1  | copying _skbuild/linux-x86_64-3.11/cmake-install/llama_cpp/libllama.so -> llama_cpp/libllama.so
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | running develop
llama-gpt-llama-gpt-api-13b-1  | /usr/local/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
llama-gpt-llama-gpt-api-13b-1  | !!
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-13b-1  |         Please avoid running ``setup.py`` directly.
llama-gpt-llama-gpt-api-13b-1  |         Instead, use pypa/build, pypa/installer or other
llama-gpt-llama-gpt-api-13b-1  |         standards-based tools.
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
llama-gpt-llama-gpt-api-13b-1  |         ********************************************************************************
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | !!
llama-gpt-llama-gpt-api-13b-1  |   self.initialize_options()
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | running egg_info
llama-gpt-llama-gpt-api-13b-1  | writing llama_cpp_python.egg-info/PKG-INFO
llama-gpt-llama-gpt-api-13b-1  | writing dependency_links to llama_cpp_python.egg-info/dependency_links.txt
llama-gpt-llama-gpt-api-13b-1  | writing requirements to llama_cpp_python.egg-info/requires.txt
llama-gpt-llama-gpt-api-13b-1  | writing top-level names to llama_cpp_python.egg-info/top_level.txt
llama-gpt-llama-gpt-api-13b-1  | reading manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-gpt-llama-gpt-api-13b-1  | adding license file 'LICENSE.md'
llama-gpt-llama-gpt-api-13b-1  | writing manifest file 'llama_cpp_python.egg-info/SOURCES.txt'
llama-gpt-llama-gpt-api-13b-1  | running build_ext
llama-gpt-llama-gpt-api-13b-1  | Creating /usr/local/lib/python3.11/site-packages/llama-cpp-python.egg-link (link to .)
llama-gpt-llama-gpt-api-13b-1  | llama-cpp-python 0.1.79 is already the active version in easy-install.pth
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Installed /app
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Processing dependencies for llama-cpp-python==0.1.79
llama-gpt-llama-gpt-api-13b-1  | Searching for diskcache==5.6.1
llama-gpt-llama-gpt-api-13b-1  | Best match: diskcache 5.6.1
llama-gpt-llama-gpt-api-13b-1  | Processing diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-13b-1  | Adding diskcache 5.6.1 to easy-install.pth file
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Using /usr/local/lib/python3.11/site-packages/diskcache-5.6.1-py3.11.egg
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Searching for numpy==1.26.0b1
llama-gpt-llama-gpt-api-13b-1  | Best match: numpy 1.26.0b1
llama-gpt-llama-gpt-api-13b-1  | Processing numpy-1.26.0b1-py3.11-linux-x86_64.egg
llama-gpt-llama-gpt-api-13b-1  | Adding numpy 1.26.0b1 to easy-install.pth file
llama-gpt-llama-gpt-api-13b-1  | Installing f2py script to /usr/local/bin
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Using /usr/local/lib/python3.11/site-packages/numpy-1.26.0b1-py3.11-linux-x86_64.egg
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Searching for typing-extensions==4.7.1
llama-gpt-llama-gpt-api-13b-1  | Best match: typing-extensions 4.7.1
llama-gpt-llama-gpt-api-13b-1  | Adding typing-extensions 4.7.1 to easy-install.pth file
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Using /usr/local/lib/python3.11/site-packages
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | Finished processing dependencies for llama-cpp-python==0.1.79
llama-gpt-llama-gpt-api-13b-1  | Initializing server with:
llama-gpt-llama-gpt-api-13b-1  | Batch size: 2096
llama-gpt-llama-gpt-api-13b-1  | Number of CPU threads: 16
llama-gpt-llama-gpt-api-13b-1  | Number of GPU layers: 0
llama-gpt-llama-gpt-api-13b-1  | Context window: 4096
llama-gpt-llama-gpt-api-13b-1  | /usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_alias" has conflict with protected namespace "model_".
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
llama-gpt-llama-gpt-api-13b-1  |   warnings.warn(
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | gguf_init_from_file: invalid magic number 67676a74
llama-gpt-llama-gpt-api-13b-1  | error loading model: llama_model_loader: failed to load model from /models/llama-2-13b-chat.bin
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  | llama_load_model_from_file: failed to load model
llama-gpt-llama-gpt-api-13b-1  | Traceback (most recent call last):
llama-gpt-llama-gpt-api-13b-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
llama-gpt-llama-gpt-api-13b-1  |   File "<frozen runpy>", line 88, in _run_code
llama-gpt-llama-gpt-api-13b-1  |   File "/app/llama_cpp/server/__main__.py", line 46, in <module>
llama-gpt-llama-gpt-api-13b-1  |
llama-gpt-llama-gpt-api-13b-1  |     app = create_app(settings=settings)
llama-gpt-llama-gpt-api-13b-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-13b-1  |   File "/app/llama_cpp/server/app.py", line 317, in create_app
llama-gpt-llama-gpt-api-13b-1  |     llama = llama_cpp.Llama(
llama-gpt-llama-gpt-api-13b-1  |             ^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-13b-1  |   File "/app/llama_cpp/llama.py", line 323, in __init__
llama-gpt-llama-gpt-api-13b-1  |     assert self.model is not None
llama-gpt-llama-gpt-api-13b-1  |            ^^^^^^^^^^^^^^^^^^^^^^
llama-gpt-llama-gpt-api-13b-1  | AssertionError
llama-gpt-llama-gpt-api-13b-1 exited with code 1

**Comment by mayankchhabra** [comment]
It's likely the model download was corrupt/incomplete. Can you manually delete the model from `models/` directory and try again?

**Comment by QuartzWarrior** [comment]
Deleted the models and tried again, same problem. If it helps, here are the model sizes that were freshly downloaded. I tried both the 7b and 13b, yes.:
Human:
```
6.9G    llama-2-13b-chat.bin
3.6G    llama-2-7b-chat.bin
```
Normal:
```
7151852 llama-2-13b-chat.bin
3702864 llama-2-7b-chat.bin
```

**Comment by 1Wayne1** [comment]
> It's likely the model download was corrupt/incomplete. Can you manually delete the model from `models/` directory and try again?

I got the same error. I try to delete the model from "models/" and  download the model again but it not worked. I also download the model from huggingface which is 'https://huggingface.co/TheBloke/Nous-Hermes-Llama2-GGML/resolve/main/nous-hermes-llama2-13b.ggmlv3.q4_0.bin' and try to run it, but the same error.

**Comment by mayankchhabra** [comment]
Sorry folks, this should be fixed now. Please see https://github.com/getumbrel/llama-gpt/issues/68#issuecomment-1694643852 on how to resolve.
