### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Whiskey-Bravo** [getumbrel/llama-gpt#68]
When i try to run the "docker compose up" command it downloads the model and then throws an AssertionError. I have tried deleting the model manually multiple times, but it still doesnt seem to work.

![image](https://github.com/getumbrel/llama-gpt/assets/86281016/9a806dd1-ce66-49ab-86b2-b0da6c451a79)

**Comment by 1Wayne1** [comment]
same issues

**Comment by RichardScottOZ** [comment]
Yes, just tried this - same here.

**Comment by RichardScottOZ** [comment]
Model works in llama.cpp so perhaps this is a new config in the model issue?

**Comment by THeivers** [comment]
Seems to be a problem with the latest version of llama.cpp from what I can gather in https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/discussions/14

I got it working locally by following the suggestion to go back to an older version, so I replaced the image version with an older one.

For example
```
 llama-gpt-api-7b:
    image: ghcr.io/abetlen/llama-cpp-python:latest
```
to
```
llama-gpt-api-7b:
    image: ghcr.io/abetlen/llama-cpp-python@sha256:b6d21ff8c4d9baad65e1fa741a0f8c898d68735fff3f3cd777e3f0c6a1839dd4
```

**Comment by mayankchhabra** [comment]
Sorry for the confusion, folks! This was resolved as a part of #71 which added support for Code Llama models. It should be fixed in the master branch now. You were correct in your assessment @THeivers. 

You can retry with:

```sh
git pull origin master
./run.sh --model 7b # or run this if you are on an M1/M2 mac: ./run-mac.sh --model 7b
```

Replace `7b` with `13b`, `70b`, `7b-code`, `13b-code`, or `34-code`.

**Comment by RichardScottOZ** [comment]
Thanks - llama.cpp is now GGUF by default and not GGML as I understand getting this working yesterday?

**Comment by Cubody** [comment]
Still have such issue
