### ISSUE TITLE
Multiuser support

### ISSUE THREAD

**Issue by badarotti** [getumbrel/llama-gpt#93]
Thanks for the great work. 
 I installed llama-gpt on a VM in my home lab and would love to give other access. Does this work as a multi-user system?
Thanks

**Comment by lukechilds** [comment]
All the data is stored client side in the browser, so multiple users can use the app and get their own isolated data. However currently only one instance of the LLM can run at the same time, so if two users where using the app at the same time, one user submitting a query would kill the other users query if it was still in progress.

**Comment by badarotti** [comment]
I guess we can manage with that for the moment. Thank you.
